title: SCMS Cloud
email: kevinpark@ciotsecurity.com
description: >- # this means to ignore newlines until "baseurl:"
  SCMS Cloud 테스트 서비스
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://scms-cloud.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  scms-cloud

theme: jekyll-theme-cayman

